job_conf_info_dict = {
    "cron":(
        "month",
        "day",
        "hour",
        "minute",
        "second"
    ),
    "interval":(
        "start_date",
        "hours",
        "minutes",
        "seconds"
    ),
    "date":(
        "year",
        "month",
        "day",
        "hour"
    )
}
